import React, { createContext, useContext, useState, ReactNode } from "react";

// Define the type for a clothing product
interface ClothingProduct {
  id: number;
  name: string;
  brand: string;
  category: string;
  price: number;
  size: string;
  color: string;
  rating: number;
  reviews: number;
  isAvailable: boolean;
  material: string;
  gender: string;
  imageUrl: string;
}

// Define the context type
interface ShopContextType {
  products: ClothingProduct[];
}

// Create the ShopContext with an empty default value
const ShopContext = createContext<ShopContextType | undefined>(undefined);

// Create a custom hook for easier access to the ShopContext

// Sample clothing products
const initialProducts: ClothingProduct[] = [
  {
    id: 1,
    name: "Classic White T-Shirt",
    brand: "Burberry",
    category: "Top wear",
    price: 199.99,
    size: "One Size",
    color: "Cream",
    rating: 4.9,
    reviews: 190,
    isAvailable: true,
    material: "Wool",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    brand: "Levi's",
    category: "Bottom wear",
    price: 49.99,
    size: "3XL",
    color: "Purple",
    rating: 4.8,
    reviews: 420,
    isAvailable: true,
    material: "Denim",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 3,
    name: "Running Shoes",
    brand: "Nike",
    category: "Bottom wear",
    price: 89.99,
    size: "L",
    color: "Black",
    rating: 4.6,
    reviews: 540,
    isAvailable: true,
    material: "Mesh",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 4,
    name: "Hooded Sweatshirt",
    brand: "Adidas",
    category: "Top wear",
    price: 59.99,
    size: "S",
    color: "White",
    rating: 4.7,
    reviews: 365,
    isAvailable: true,
    material: "Polyester",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 5,
    name: "Casual Chinos",
    brand: "Zara",
    category: "Bottom wear",
    price: 39.99,
    size: "M",
    color: "Blue",
    rating: 4.3,
    reviews: 280,
    isAvailable: true,
    material: "Cotton",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 6,
    name: "Floral Print Dress",
    brand: "H&M",
    category: "Top wear",
    price: 29.99,
    size: "XS",
    color: "Red",
    rating: 4.4,
    reviews: 180,
    isAvailable: true,
    material: "Rayon",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 7,
    name: "Denim Jacket",
    brand: "Guess",
    category: "Top wear",
    price: 69.99,
    size: "2XL",
    color: "Cream",
    rating: 4.6,
    reviews: 320,
    isAvailable: true,
    material: "Denim",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 8,
    name: "Striped Polo Shirt",
    brand: "Ralph Lauren",
    category: "Top wear",
    price: 79.99,
    size: "XXS",
    color: "Green",
    rating: 4.5,
    reviews: 150,
    isAvailable: true,
    material: "Cotton",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 9,
    name: "Yoga Leggings",
    brand: "Lululemon",
    category: "Bottom wear",
    price: 89.99,
    size: "XL",
    color: "Grey",
    rating: 4.9,
    reviews: 610,
    isAvailable: true,
    material: "Spandex",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 10,
    name: "Puffer Jacket",
    brand: "The North Face",
    category: "Top wear",
    price: 149.99,
    size: "5XL",
    color: "Blue",
    rating: 4.8,
    reviews: 410,
    isAvailable: true,
    material: "Nylon",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 11,
    name: "Leather Chelsea Boots",
    brand: "Dr. Martens",
    category: "Bottom wear",
    price: 139.99,
    size: "M",
    color: "Brown",
    rating: 4.7,
    reviews: 290,
    isAvailable: true,
    material: "Leather",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 12,
    name: "Basic Black Cap",
    brand: "New Era",
    category: "Top wear",
    price: 19.99,
    size: "One Size",
    color: "Black",
    rating: 4.4,
    reviews: 200,
    isAvailable: true,
    material: "Cotton",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 13,
    name: "Oversized Hoodie",
    brand: "Champion",
    category: "Top wear",
    price: 44.99,
    size: "XS",
    color: "Pink",
    rating: 4.5,
    reviews: 340,
    isAvailable: true,
    material: "Fleece",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 14,
    name: "Plaid Flannel Shirt",
    brand: "Uniqlo",
    category: "Top wear",
    price: 34.99,
    size: "L",
    color: "White",
    rating: 4.3,
    reviews: 270,
    isAvailable: true,
    material: "Cotton",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 15,
    name: "Athletic Shorts",
    brand: "Under Armour",
    category: "Bottom wear",
    price: 29.99,
    size: "XXS",
    color: "Purple",
    rating: 4.6,
    reviews: 310,
    isAvailable: true,
    material: "Polyester",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 16,
    name: "Wool Scarf",
    brand: "Burberry",
    category: "Inner wear",
    price: 199.99,
    size: "One Size",
    color: "Cream",
    rating: 4.9,
    reviews: 190,
    isAvailable: true,
    material: "Wool",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 17,
    name: "V-Neck Sweater",
    brand: "Tommy Hilfiger",
    category: "Top wear",
    price: 69.99,
    size: "L",
    color: "Green",
    rating: 4.4,
    reviews: 230,
    isAvailable: true,
    material: "Wool",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 18,
    name: "High-Waist Skirt",
    brand: "Forever 21",
    category: "Bottom wear",
    price: 24.99,
    size: "S",
    color: "Black",
    rating: 4.2,
    reviews: 150,
    isAvailable: true,
    material: "Polyester",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 19,
    name: "Button-Up Shirt",
    brand: "Calvin Klein",
    category: "Top wear",
    price: 49.99,
    size: "M",
    color: "White",
    rating: 4.6,
    reviews: 310,
    isAvailable: true,
    material: "Cotton",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 20,
    name: "Graphic Tee",
    brand: "Supreme",
    category: "Top wear",
    price: 39.99,
    size: "XS",
    color: "Red",
    rating: 4.8,
    reviews: 500,
    isAvailable: true,
    material: "Cotton",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 21,
    name: "Cargo Pants",
    brand: "Patagonia",
    category: "Bottom wear",
    price: 59.99,
    size: "XL",
    color: "Brown",
    rating: 4.7,
    reviews: 280,
    isAvailable: true,
    material: "Cotton",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 22,
    name: "Track Jacket",
    brand: "Puma",
    category: "Top wear",
    price: 79.99,
    size: "2XL",
    color: "Blue",
    rating: 4.5,
    reviews: 290,
    isAvailable: true,
    material: "Polyester",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 23,
    name: "Silk Blouse",
    brand: "Dior",
    category: "Top wear",
    price: 129.99,
    size: "XXS",
    color: "Pink",
    rating: 4.9,
    reviews: 400,
    isAvailable: true,
    material: "Silk",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 24,
    name: "Sport Socks (5-Pack)",
    brand: "Adidas",
    category: "Inner wear",
    price: 19.99,
    size: "2XL",
    color: "Black",
    rating: 4.3,
    reviews: 120,
    isAvailable: true,
    material: "Cotton",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 25,
    name: "Polo Shirt",
    brand: "Lacoste",
    category: "Top wear",
    price: 89.99,
    size: "3XL",
    color: "Green",
    rating: 4.6,
    reviews: 210,
    isAvailable: true,
    material: "Cotton",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 26,
    name: "Sports Bra",
    brand: "Nike",
    category: "Inner wear",
    price: 34.99,
    size: "XS",
    color: "White",
    rating: 4.9,
    reviews: 430,
    isAvailable: true,
    material: "Spandex",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 27,
    name: "Leather Biker Jacket",
    brand: "AllSaints",
    category: "Top wear",
    price: 299.99,
    size: "L",
    color: "Black",
    rating: 4.8,
    reviews: 330,
    isAvailable: true,
    material: "Leather",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 28,
    name: "Corduroy Pants",
    brand: "Urban Outfitters",
    category: "Bottom wear",
    price: 54.99,
    size: "M",
    color: "Brown",
    rating: 4.5,
    reviews: 190,
    isAvailable: true,
    material: "Corduroy",
    gender: "Men",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 29,
    name: "Ankle Boots",
    brand: "Steve Madden",
    category: "Bottom wear",
    price: 119.99,
    size: "L",
    color: "Cream",
    rating: 4.7,
    reviews: 240,
    isAvailable: true,
    material: "Leather",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 30,
    name: "Denim Skirt",
    brand: "American Eagle",
    category: "Bottom wear",
    price: 44.99,
    size: "S",
    color: "Blue",
    rating: 4.6,
    reviews: 260,
    isAvailable: true,
    material: "Denim",
    gender: "Women",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
  {
    id: 31,
    name: "Wide Brim Hat",
    brand: "Stetson",
    category: "Top wear",
    price: 99.99,
    size: "XXS",
    color: "Grey",
    rating: 4.8,
    reviews: 310,
    isAvailable: true,
    material: "Wool",
    gender: "Unisex",
    imageUrl: "https://d22po4pjz3o32e.cloudfront.net/placeholder-image.svg",
  },
];

// Create the ShopProvider component to wrap around the app
export const ShopContextProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const [products] = useState<ClothingProduct[]>(initialProducts);

  return (
    <ShopContext.Provider value={{ products }}>{children}</ShopContext.Provider>
  );
};

export const useShop = () => {
  const context = useContext(ShopContext);
  if (!context) {
    throw new Error("useShop must be used within a ShopProvider");
  }
  return context;
};
